#ifndef _DEFINE_H_
#define _DEFINE_H_




#define DEC_1   0 
#define DEC_2   1 
#define DEC_3   2 
#define DEC_4   3 
#define DEC_5   4 
#define DEC_6   5 
#define DEC_7   6 
#define DEC_8   7 
#define DEC_9   8 
#define DEC_10   9 
#define DEC_11  10
#define DEC_12  11
#define DEC_13  12
#define DEC_14  13
#define DEC_15  14
#define DEC_16  15
#define DEC_17  16
#define DEC_18  17
#define DEC_19  18
#define DEC_20  19
#define DEC_21  20
#define DEC_22  21
#define DEC_23  22
#define DEC_24  23
#define DEC_25  24
#define DEC_26  25
#define DEC_27  26
#define DEC_28  27
#define DEC_29  28
#define DEC_30  29
#define DEC_31  30
#define DEC_32  31

#define DEC(n)  DEC_##n

#if 1
#define INTERFACE_FUNC(n) \
virtual bool Interface_func##n(const Json::Value attr, ICallBack* callback = NULL )\
{\
	return False;\
};
#else
#define INTERFACE_FUNC(n) INTERFACE_FUNC1(n)
#define INTERFACE_FUNC1(n) \
virtual bool Interface_func##n(const Json::Value attr) = 0;
#endif

#define INTERFACE_FUNC_REALIZATION(n) INTERFACE_FUNC(n)

#define INTERFACE_FUNC_RESERVED(n) INTERFACE_FUNC_RESERVED_##n(n)

#define INTERFACE_FUNC_RESERVED_32(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_31(DEC(n))

#define INTERFACE_FUNC_RESERVED_31(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_30(DEC(n))

#define INTERFACE_FUNC_RESERVED_30(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_29(DEC(n))

#define INTERFACE_FUNC_RESERVED_29(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_28(DEC(n))

#define INTERFACE_FUNC_RESERVED_28(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_27(DEC(n))

#define INTERFACE_FUNC_RESERVED_27(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_26(DEC(n))

#define INTERFACE_FUNC_RESERVED_26(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_25(DEC(n))

#define INTERFACE_FUNC_RESERVED_25(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_24(DEC(n))

#define INTERFACE_FUNC_RESERVED_24(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_23(DEC(n))

#define INTERFACE_FUNC_RESERVED_23(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_22(DEC(n))

#define INTERFACE_FUNC_RESERVED_22(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_21(DEC(n))

#define INTERFACE_FUNC_RESERVED_21(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_20(DEC(n))

#define INTERFACE_FUNC_RESERVED_20(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_19(DEC(n))

#define INTERFACE_FUNC_RESERVED_19(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_18(DEC(n))

#define INTERFACE_FUNC_RESERVED_18(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_17(DEC(n))

#define INTERFACE_FUNC_RESERVED_17(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_16(DEC(n))

#define INTERFACE_FUNC_RESERVED_16(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_15(DEC(n))

#define INTERFACE_FUNC_RESERVED_15(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_14(DEC(n))

#define INTERFACE_FUNC_RESERVED_14(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_13(DEC(n))

#define INTERFACE_FUNC_RESERVED_13(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_12(DEC(n))

#define INTERFACE_FUNC_RESERVED_12(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_11(DEC(n))

#define INTERFACE_FUNC_RESERVED_11(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_10(DEC(n))

#define INTERFACE_FUNC_RESERVED_10(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_9(DEC(n))

#define INTERFACE_FUNC_RESERVED_9(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_8(DEC(n))

#define INTERFACE_FUNC_RESERVED_8(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_7(DEC(n))

#define INTERFACE_FUNC_RESERVED_7(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_6(DEC(n))

#define INTERFACE_FUNC_RESERVED_6(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_5(DEC(n))

#define INTERFACE_FUNC_RESERVED_5(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_4(DEC(n))

#define INTERFACE_FUNC_RESERVED_4(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_3(DEC(n))

#define INTERFACE_FUNC_RESERVED_3(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_2(DEC(n))

#define INTERFACE_FUNC_RESERVED_2(n) \
INTERFACE_FUNC_REALIZATION(n)\
INTERFACE_FUNC_RESERVED_1(DEC(n))

#define INTERFACE_FUNC_RESERVED_1(n) \
INTERFACE_FUNC_REALIZATION(n)





#endif//_DEFINE_H_
